development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: rediss://default:<%= Rails.application.secrets.redis_password %>@private-redis-do-user-244497-0.a.db.ondigitalocean.com:25061
