name: Deploy
on:
  push:
    branches: [master]
runs-on: ubuntu-latest
jobs:
  deploy:
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: placeholder
      - name: Adding host to known hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Run deploy script
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '/home/rails/bin/deploy'
