name: Tests
on: [ push ]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
          bundler-cache: true
      - name: Create database
        run: |
          bin/rails db:prepare
      - name: Run tests
        run: |
          bin/bundle exec rake
